name: static_analysis

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

env:
  # Expected error count should decrease as we handle the errors. Update accordingly.
  CPPCHECK_EXPECTED_ERROR_COUNT: 42

jobs:
  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install 
        shell: bash
        run: |
          sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
          sudo apt-get update;
          sudo apt-get install -qq cppcheck;
      
      - name: Run
        shell: bash
        #Selected run options:
        #  .            :   Run on all files in librealsense folder
        #  --quiet      :   Don't show current checked configuration in log
        #  --std=c++11  :   Use C++11 standard (default but worth mentioning)
        #  -I           :   Include directories
        #  -i           :   Ignore direcrories. Ignore third-party libs that we don't want to check
        #  --suppress   :   Don't issue errors about files matching the expression (when -i for folders is not enough)
        #  --xml        :   Output in XML format
        run: | 
          cppcheck ./src ./include ./common ./tools ./third-party/realdds ./third-party/utilities --quiet --std=c++11 -I./src -I./include -I./third-party/utilities/include -I./common --suppress=*:third-party/json.hpp --xml &> cppcheck_run.log

      - name: Upload log
        uses: actions/upload-artifact@v3
        with: 
          name: cppcheck_log
          path: cppcheck_run.log

      - name: Provide correct exit status
        shell: bash
        run: |
          ERROR_COUNT=$(grep cppcheck_run.log -e "severity=\"error\"" -c);
          if [ $ERROR_COUNT == ${{env.CPPCHECK_EXPECTED_ERROR_COUNT}} ];
          then
            echo "cppcheck_run succeeded, found" $ERROR_COUNT "errors, as expected";
            exit 0;
          else
            echo "cppcheck_run failed, found" $ERROR_COUNT "errors, see log for details";
            exit 1;
          fi