name: static_analisys

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)  
  CPPCHECK_EXPECTED_ERROR_COUNT: 53

jobs:
  cppcheck:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cppcheck
        shell: bash
        run: |
          sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
          sudo apt-get update;
          sudo apt-get install -qq cppcheck;
      
      - name: Run cppcheck
        shell: bash
        run: | 
          cppcheck . --enable=all --verbose --std=c++11 -ithird-party/easyloggingpp -ithird-party/glad -ithird-party/sqlite -ithird-party/imgui -ithird-party/glfw -ithird-party/hidapi -ithird-party/json.hpp --xml &> cppcheck_run.log

      - name: Upload cppcheck log
        uses: actions/upload-artifact@v3
        with: 
          name: cppcheck_log
          path: cppcheck_run.log

      - name: Provide correct exit status for job 
        shell: bash
        run: |
          ERROR_COUNT=$(grep cppcheck_run.log -e "severity=\"error\"" -c);
          if [ $ERROR_COUNT == ${{env.CPPCHECK_EXPECTED_ERROR_COUNT}} ];
          then
            echo "cppcheck_run succeeded, found" $ERROR_COUNT "errors, as expected";
            exit 0;
          else
            echo "cppcheck_run failed, found" $ERROR_COUNT "errors, see log for details";
            exit 1;
          fi